VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IHookSink"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' Credit to Karl E. Peterson for the idea to put this into a class
' Credit to vbaccelerator: Subclassing Without The Crashes

Public Function WindowProc(hWnd As Long, msg As Long, wp As Long, lp As Long) As Long
End Function


